-- 004_alias_zonage.sql
-- Lot 0.5 — codes spatiaux → codes de corpus.textes
-- Idempotent. Ne touche pas aux schémas par commune.

CREATE TABLE IF NOT EXISTS corpus.alias_zonage (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  commune_insee   text NOT NULL,
  document_type   text NOT NULL,
  code_spatial    text NOT NULL,
  code_texte      text NOT NULL,
  commentaire     text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (commune_insee, document_type, code_spatial, code_texte)
);

COMMENT ON TABLE corpus.alias_zonage IS
  'Correspondance code cartographique → zone_code de corpus.textes. '
  'Plusieurs lignes par code spatial (ex. UA → UAa et UAb).';

CREATE INDEX IF NOT EXISTS alias_zonage_lookup
  ON corpus.alias_zonage (commune_insee, document_type, upper(code_spatial));

-- PLU Argelès : le GPU porte UA, le règlement est découpé UAa / UAb.
INSERT INTO corpus.alias_zonage
  (commune_insee, document_type, code_spatial, code_texte, commentaire)
VALUES
  ('66008', 'PLU', 'UA', 'UAa', 'GPU zonage_reglement=UA, règlement UAa'),
  ('66008', 'PLU', 'UA', 'UAb', 'GPU zonage_reglement=UA, règlement UAb')
ON CONFLICT (commune_insee, document_type, code_spatial, code_texte) DO NOTHING;

-- PPR Argelès : label de sous-zone (I-b2, II-a, …) → bloc I / II / III.
INSERT INTO corpus.alias_zonage
  (commune_insee, document_type, code_spatial, code_texte, commentaire)
SELECT DISTINCT
  '66008',
  'PPR',
  btrim(p.label),
  btrim(p.code_degre),
  'label spatial PPR → zone_code règlement'
FROM argeles.ppr p
WHERE p.code_degre IN ('I', 'II', 'III')
  AND p.label IS NOT NULL
  AND btrim(p.label) <> ''
ON CONFLICT (commune_insee, document_type, code_spatial, code_texte) DO NOTHING;

-- PPR : code_degre lui-même (au cas où il est passé comme code spatial).
INSERT INTO corpus.alias_zonage
  (commune_insee, document_type, code_spatial, code_texte, commentaire)
SELECT DISTINCT
  '66008',
  'PPR',
  btrim(p.code_degre),
  btrim(p.code_degre),
  'identité code_degre'
FROM argeles.ppr p
WHERE p.code_degre IN ('I', 'II', 'III')
ON CONFLICT (commune_insee, document_type, code_spatial, code_texte) DO NOTHING;

-- PPRIF Argelès : label / code_degre → R, B1–B4 s'ils matchent un zone_code corpus.
INSERT INTO corpus.alias_zonage
  (commune_insee, document_type, code_spatial, code_texte, commentaire)
SELECT DISTINCT
  '66008',
  'PPRIF',
  btrim(p.label),
  t.zone_code,
  'label spatial PPRIF → zone_code règlement'
FROM argeles.pprif p
JOIN corpus.textes t
  ON t.commune_insee = '66008'
 AND t.document_type = 'PPRIF'
 AND t.zone_code IS NOT NULL
 AND t.portee IS DISTINCT FROM 'globale'
 AND (
      upper(replace(btrim(p.label), ' ', '')) = upper(t.zone_code)
   OR upper(btrim(p.code_degre)) = upper(t.zone_code)
   OR (p.label ~* 'rouge' AND t.zone_code = 'R')
 )
WHERE p.label IS NOT NULL AND btrim(p.label) <> ''
ON CONFLICT (commune_insee, document_type, code_spatial, code_texte) DO NOTHING;

-- PPRI Latresne : codezone / nom GPU → zone_code corpus (BLEUE, ROUGE_URBA, …)
INSERT INTO corpus.alias_zonage
  (commune_insee, document_type, code_spatial, code_texte, commentaire)
SELECT DISTINCT
  '33234',
  'PPRI',
  btrim(p.codezone),
  t.zone_code,
  'PM1 codezone → PPRI corpus'
FROM latresne.pm1_detaillee_gironde p
JOIN corpus.textes t
  ON t.commune_insee = '33234'
 AND t.document_type = 'PPRI'
 AND t.zone_code IS NOT NULL
 AND t.portee IS DISTINCT FROM 'globale'
 AND (
      upper(btrim(p.codezone)) = upper(t.zone_code)
   OR upper(replace(replace(btrim(coalesce(p.nom, '')), ' ', '_'), '-', '_'))
      = upper(t.zone_code)
 )
WHERE p.codezone IS NOT NULL AND btrim(p.codezone) <> ''
ON CONFLICT (commune_insee, document_type, code_spatial, code_texte) DO NOTHING;

-- PPRMVT Latresne : identité codezone si le code GPU diffère en casse/espaces
INSERT INTO corpus.alias_zonage
  (commune_insee, document_type, code_spatial, code_texte, commentaire)
SELECT DISTINCT
  '33234',
  'PPRMVT',
  btrim(p.codezone),
  t.zone_code,
  'PPRMVT codezone → corpus'
FROM latresne.pprmvt p
JOIN corpus.textes t
  ON t.commune_insee = '33234'
 AND t.document_type = 'PPRMVT'
 AND t.zone_code IS NOT NULL
 AND t.portee IS DISTINCT FROM 'globale'
 AND upper(btrim(p.codezone)) = upper(t.zone_code)
WHERE p.codezone IS NOT NULL AND btrim(p.codezone) <> ''
ON CONFLICT (commune_insee, document_type, code_spatial, code_texte) DO NOTHING;

CREATE OR REPLACE FUNCTION corpus.resoudre_codes_zonage(
  p_insee text,
  p_document_type text,
  p_codes text[]
)
RETURNS text[]
LANGUAGE sql
STABLE
AS $function$
  WITH demandes AS (
    SELECT DISTINCT btrim(c) AS code
    FROM unnest(coalesce(p_codes, ARRAY[]::text[])) AS c
    WHERE c IS NOT NULL AND btrim(c) <> ''
  ),
  via_alias AS (
    SELECT a.code_texte AS code
    FROM demandes d
    JOIN corpus.alias_zonage a
      ON a.commune_insee = p_insee
     AND a.document_type = p_document_type
     AND upper(a.code_spatial) = upper(d.code)
  ),
  sans_alias AS (
    SELECT d.code
    FROM demandes d
    WHERE NOT EXISTS (
      SELECT 1
      FROM corpus.alias_zonage a
      WHERE a.commune_insee = p_insee
        AND a.document_type = p_document_type
        AND upper(a.code_spatial) = upper(d.code)
    )
  )
  SELECT coalesce(
    array_agg(DISTINCT x.code ORDER BY x.code),
    ARRAY[]::text[]
  )
  FROM (
    SELECT code FROM via_alias
    UNION ALL
    SELECT code FROM sans_alias
  ) x;
$function$;

COMMENT ON FUNCTION corpus.resoudre_codes_zonage(text, text, text[]) IS
  'Remplace chaque code spatial par ses code_texte d''alias s''il en existe, '
  'sinon conserve le code tel quel.';
